### ISSUE TITLE
Font not aligning with Screen

### ISSUE THREAD

**Issue by superstap** [z1pti3/jimi#108]
![image](https://user-images.githubusercontent.com/21224929/113033992-4abfb180-919a-11eb-8341-a40f7bf0457f.png)

**Comment by z1pti3** [comment]
Hi Superstap,

Could you provide:
Browser
Resolution
OS
Scaling settings

Thanks
Z1P

**Comment by superstap** [comment]
Hello Z1pti3,

Browser: Chrome version 89.0.4389.114
Resolution: 2560 x 1440
OS: Windows 10 Pro 20H2
Scaling settings: 125%

Regards,
Superstap

**Comment by z1pti3** [comment]
Fixed in latest 2.1 build
