### ISSUE TITLE
Docker Installation Permissions Bug

### ISSUE THREAD

**Issue by superstap** [z1pti3/jimi#109]
The Docker volume permissions are set to UID 1000 which is the jimi user when created on a system if another user (other than root) does not exist on the system. Therefore, on a system in which other users there is a permission issue.

to fix that: 
(REPLACE 1001:1001 with the local user UID:GID) 
docker run -it -u 1001:1001 -d -v /home/jimi/data:/home/jimi/jimi/data -v /home/jimi/plugins:/home/jimi/jimi/plugins --net jimi_network --name jimi_core z1pti3/jimi_core:amd64

docker run -it -u 1001:1001  -d -p 4443:4443 -v /home/jimi/data:/home/jimi/jimi/data -v /home/jimi/plugins:/home/jimi/jimi/plugins --net jimi_network --name jimi_web z1pti3/jimi_web:amd64

**Comment by z1pti3** [comment]
Updated the installer file so that it now automatically uses the user and group id for the create jimi user

-u `id -u jimi`:`id -g jimi`
