### ISSUE TITLE
ACL to prevent adding new objects but allow reading

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#112]
How can I setup the permission on a model so that it can be read to prevent unknown object but not allow users to create new objects of that class ?

**Comment by z1pti3** [comment]
Removed sessionData checks for getClassObject which is used to return empty classes that are then filled by data loaded within the data. The data loading from the database is subject to a db.query function that does require sessionData and therefore enforces ACL.

The advantage of this is that objects can now be set to readable without allowing users to add new objects of the same type.

![image](https://user-images.githubusercontent.com/66521110/123486796-a3b9ad00-d604-11eb-8e0e-d4d4a1f8cf09.png)

sessionData is left on the function calls as this is a requirement of cache

**Comment by z1pti3** [comment]
Added fix to allow edit and export of readable objects - read on model still required for creating new objects.
