### ISSUE TITLE
File system syncing not working as expected

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#116]
File system syncing not working as expected as it seems to miss files and then does not sync from the target system correctly

**Comment by z1pti3** [comment]
Hi,

If you use the new API can you see which files are not syncing as expected?

/api/1.0/system/checksum/<SourceSystem>/<TargetSystem>/

**Comment by u-n-i-c-o-rn** [comment]
After checking this I could see some bugs so updated the code to fix the issue with sync.

https://github.com/z1pti3/jimi/pull/207
