### ISSUE TITLE
unicodeEscapeDict function assumes all keys are strings

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#120]
Came across this issue today.
When attempting to update a dictionary object in the database, the DB class calls the unicodeEscapeDict function:
https://github.com/z1pti3/jimi/blob/e79aed10890b4af0c94adf61f4325d8982ffef39/core/db.py#L117-L122

However, this assumes that all keys in the dictionary are strings, as it attempts to do a replace on the key on line 345.
https://github.com/z1pti3/jimi/blob/e79aed10890b4af0c94adf61f4325d8982ffef39/core/helpers.py#L342-L358

This function should probably check that the key is a string, or skip this check. I think a try-except would be the most efficient, but @z1pti3 will know best!

**Comment by z1pti3** [comment]
What error did you get / were doing at the time the issue occurred?
________________________________
From: Patrick Lynch ***@***.***>
Sent: Tuesday, May 11, 2021 5:38:59 PM
To: z1pti3/jimi ***@***.***>
Cc: z1pti3 ***@***.***>; Mention ***@***.***>
Subject: [z1pti3/jimi] unicodeEscapeDict function assumes all keys are strings (#120)


Came across this issue today.
When attempting to update a dictionary object in the database, the DB class calls the unicodeEscapeDict function:
https://github.com/z1pti3/jimi/blob/e79aed10890b4af0c94adf61f4325d8982ffef39/core/db.py#L117-L122<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fz1pti3%2Fjimi%2Fblob%2Fe79aed10890b4af0c94adf61f4325d8982ffef39%2Fcore%2Fdb.py%23L117-L122&data=04%7C01%7C%7Caba537508a8e422efb4208d9149b4786%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637563479408179176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Rxvf7RawyN3a%2Bv0aenQs%2FNDmtV8MU%2FoWoQV8CdHgEQQ%3D&reserved=0>

However, this assumes that all keys in the dictionary are strings
https://github.com/z1pti3/jimi/blob/e79aed10890b4af0c94adf61f4325d8982ffef39/core/helpers.py#L342-L358<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fz1pti3%2Fjimi%2Fblob%2Fe79aed10890b4af0c94adf61f4325d8982ffef39%2Fcore%2Fhelpers.py%23L342-L358&data=04%7C01%7C%7Caba537508a8e422efb4208d9149b4786%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637563479408189131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T829rPONcV1IXEtS0F8Q9rWEom1aNgOhWCgYRiinvF8%3D&reserved=0>

This function should probably check that the key is a string, or skip this check. I think a try-except would be the most efficient, but @z1pti3<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fz1pti3&data=04%7C01%7C%7Caba537508a8e422efb4208d9149b4786%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637563479408189131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kv7NBO%2F1TI4fRQ2ZisUTI7RsgeV63546NpKCpMraDyc%3D&reserved=0> will know best!

**Comment by b1scuit-thi3f** [comment]
` File "C:\Users\patrick\source\repos\jimi-opensource\core\db.py", line 121, in update
  File "C:\Users\patrick\source\repos\jimi-opensource\core\helpers.py", line 327, in unicodeEscapeDict
    newKey = key.replace(".","\\u002E").replace("$","\\u0024")
AttributeError: 'int' object has no attribute 'replace'`

I was attempting to update a field within a custom collection. This field expected a dictionary, but the dictionary I provided used integers for keys (due to the source I was pulling them from) rather than strings. Of course, a workaround was for me to convert the ints into strings first, but I feel flexibility on JIMI's end should be made, as there are genuine reasons why a dictionary might have integer keys (such as IDs).

**Comment by u-n-i-c-o-rn** [comment]
This set of code is a bit inefficient as well as this replace is run on every key pulled back, do we have a option around making this code only execute when needed?

**Comment by z1pti3** [comment]
As suggested a try except would be the most efficient for this given the use of int keys. I do agree with unicorn that we should be looking at how we can reduce the calls made to replace on every document we load.

**Comment by z1pti3** [comment]
No major issues found with performance using this function. We will look at this again in the future if required.
