### ISSUE TITLE
[Feature] cluster groups to keep clusters apart

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#125]
Cluster groups within jimi are used to ensure the same jobs run on the same cluster member. There is however no logic to try and keep separate cluster groups on different cluster members. 

This feature would help when large jobs execute on the same nodes and could be used to help keep these on different nodes

**Comment by z1pti3** [comment]
v3.0 will handle the balancing of this without the need for keeping servers apart.
