### ISSUE TITLE
Encrypt/Decrypt JIMI Eval Function

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#126]
Given the recent change pushed to Remote to support variable replacement syntax in the password field:
https://github.com/z1pti3/jimiPlugin-remote/commit/fca7dadaeab052c912a1f6ac269a7ea5b28d1781

I think it would be beneficial to encrypt and decrypt values within the replacement syntax. This would allow a user to encrypt a value dynamically so that even if someone was to inspect the flow while it was running (via logging or debug mode) they wouldn't be able to identify any sensitive information such as a password.

This function should be able to replicate what the current encryption function for sensitive fields does.

**Comment by z1pti3** [comment]
It would be good to change this function so that it uses a custom defined key for the AES instead of the system key. This would enable the use of encryption and decryption but without the risk of users gaining access to all secrets that are stored securely currently.

**Comment by b1scuit-thi3f** [comment]
Added https://github.com/z1pti3/jimi/commit/218dba58772c49fee61171de72556c38ab66d781 as a first step. I'm not sure if we need to look at one might be able to keep the password set in the second parameter secret, but maybe that is overcomplicating things, as the main purpose of this is to obstruct the password from being visible during the flow
@z1pti3 what are your thoughts?

**Comment by z1pti3** [comment]
Are you planning just for execution? If it is just for execution then you could dynamically and randomly set the encryption key stored into persistentData encrypted using jimi inbuilt encryption? - This could always be the default behaviour if you dont supply an encpytion key?

1. Check if persistentData contains decryption key
2. Generate if missing ( randomly )  + ENC using inbuild jimi encryption
3. Load from persistentData and decrypt using ENC from inbuilt jimi decryption leaving you with plaintext random encption key to use
4. Use the plaintext key to encrypt the string / decrypt the string

Or something like this?

**Comment by b1scuit-thi3f** [comment]
That's a good idea, I'll at adding that functionality in.
