### ISSUE TITLE
Jimi latest code does not authenticate post first install

### ISSUE THREAD

**Issue by superstap** [z1pti3/jimi#168]
Freshly cloned the code, followed manual steps and got jimi core & web running. However, using the newly generated password from jimi_core, does not authenticate on the web-portal.

**To Reproduce**
1) follow all manual steps within jimi-docs
2) Navigate to web-gui
3) Attempt to authenticate using root:<jimi_core-generated password)
4) See error

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version 91.0.4472.164

**Comment by z1pti3** [comment]
What error do you see? I just ran this steps on a blank DB form start to finish and had no issues.

**Comment by superstap** [comment]
Hello,

I've managed to recreate and identify what the issue might be.

Lab infrastructure:
Server: Debian 10 Server running jimi
Client: Windows 10

Secure cookie attribute when running on localhost is bypassed, but when connected through the client the browser fails to set the cookie when successfully authenticating.

This was proven when the jimi port was redirected through an SSH session.


Workaround:

Edit file jimi/core/auth.py

Find line  from:
response.set_cookie("jimiAuth", value=userSession, max_age=authSettings["sessionTimeout"], httponly=True,Secure=True)

to:
response.set_cookie("jimiAuth", value=userSession, max_age=authSettings["sessionTimeout"], httponly=True)

And rebind web within settings.json to: 0.0.0.0

**Comment by z1pti3** [comment]
Fixed by adding an option for webSecure into config:

"secure" : {
    "cert" : "certPath",
    "key" : "privateKeyPath"
}

These settings go into api -> web
