### ISSUE TITLE
[Bug] - forEach with concurrency much slower than without  

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#186]
forEach with concurrency much slower than without 

![image](https://user-images.githubusercontent.com/81556695/129734958-91b432a3-4df1-4467-a039-0469838b2899.png)

**Comment by b1scuit-thi3f** [comment]
Closed the wrong issue... Meant to close #187

**Comment by z1pti3** [comment]
CPU seems very high when using this feature

**Comment by z1pti3** [comment]
There is an overhead that forEach will always encounter as it spawns the threads so usage should only be when the flow it executes is slow performance i.e. external script or process.
