### ISSUE TITLE
[Bug] - Save ( number ) is now missing from UI

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#187]
There used to be a number on the save button this is now missing?

![image](https://user-images.githubusercontent.com/81556695/129735050-d300ba56-cfba-4f19-ae50-ad36c9cba066.png)

**Comment by b1scuit-thi3f** [comment]
Fixed in https://github.com/z1pti3/jimi/commit/a8e2084fde1d6356c9066f5ce2145fd92e60831f
