### ISSUE TITLE
[Bug] - Flow export with loop hangs

### ISSUE THREAD

**Issue by z1pti3** [z1pti3/jimi#193]
Attempting to export a single flow from within a conduct containing a loop hangs and never completes. Exporting the whole conduct does work.

![image](https://user-images.githubusercontent.com/66521110/130359268-c0c4d28f-97ed-48e0-9666-8023412e54e0.png)

**Comment by b1scuit-thi3f** [comment]
Hi @z1pti3,
I've pushed 0014a56ba88bcee26cae6848f5725c998a8607cd, let me know if that fixes your issue!
