### ISSUE TITLE
[Bug] Importing flows that have objects with the same name but different settings results in incorrect import

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#195]
If you import a flow that contains objects that share the same name then import overwrites them so they each have the same content.

 
![image](https://user-images.githubusercontent.com/81556695/130766906-60b98208-6fb8-4db7-8cf1-541884c77abb.png)

These have different content but now they are the same object

![image](https://user-images.githubusercontent.com/81556695/130766955-de23c6e8-889d-43ba-962c-0d8e6449c3c2.png)

**Comment by b1scuit-thi3f** [comment]
We could look at providing an object hash - this would allow us to generate a hash based on a number of different fields (perhaps just excluding certain system fields). That way the system wouldn't have to rely on fuzzy matching.

**Comment by z1pti3** [comment]
Did not add as a hash but compared the values of each field to make sure there are no differences on the target object.
