### ISSUE TITLE
[Bug] Debug showing exception but trigger does not fail

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#198]
I have a flow built that uses a trigger into a forEach and due to a /0 error as shown in debug the trigger should be failing. This is not happening but instead the trigger continues 

![image](https://user-images.githubusercontent.com/81556695/130952585-efa699b6-9dcc-451e-93b2-7bcfbc3132bb.png)

![image](https://user-images.githubusercontent.com/81556695/130952620-276a56a6-fdb7-495d-b4a9-78ed421e8c57.png)

![image](https://user-images.githubusercontent.com/81556695/130952644-af6f76d8-76c8-4731-9c6b-055d318c853c.png)

I would have expected the trigger to fail when this exception is raised

**Comment by z1pti3** [comment]
Recreated but only affects triggers that are running in threaded mode
