### ISSUE TITLE
Administration of Users does not have a clear button

### ISSUE THREAD

**Issue by superstap** [z1pti3/jimi#201]
Within /admin/users, adding a new user and filling the page, then clicking away because you want to cancel. By clicking add user again, the form is pre-filled with no option to clear.

**Comment by b1scuit-thi3f** [comment]
@superstap I've now added some functionality to clear the form when you click away. Do you feel this needs a "clear" button or are you happy with the solution?

**Comment by b1scuit-thi3f** [comment]
Discussed with requestor on other channels and d921b815c726e169c5a35f01a81eea8a75b8321d is perhaps a better and more elegant solution.
