### ISSUE TITLE
[Bug] Export assumes temp folder exists

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#211]
https://github.com/z1pti3/jimi/blob/f707258b14b5de648a9826611e05e0768e2f339e/web/conductEditor.py#L345

Export assumes the data folder contains another folder called temp

**Comment by u-n-i-c-o-rn** [comment]
![image](https://user-images.githubusercontent.com/81556695/132518013-5475b056-25a3-49dc-a870-01e9548d05dc.png)

**Comment by z1pti3** [comment]
Temp folder is part of standard install requirements
