### ISSUE TITLE
[Bug] Type cast within jimiFlows does not work with list of a list

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#224]
if you try and type cast the following it gets converted into a single list

[[1,2],[1,2]] becomes [1,2,1,2]

**Comment by b1scuit-thi3f** [comment]
Hi @u-n-i-c-o-rn,
I can't seem to replicate this in my flow but I have a feeling it's possibly just a GUI bug. Could you confirm that you only see this in Debug and not if say you output to the CLI using testFire?

**Comment by b1scuit-thi3f** [comment]
Issue should now be resolved. Please reopen if not the case!
