### ISSUE TITLE
[Bug] checksum is slow when large storage files are used

### ISSUE THREAD

**Issue by z1pti3** [z1pti3/jimi#227]
checksum is slow when large storage files are used due to the way the sha is generated.

**Comment by b1scuit-thi3f** [comment]
@z1pti3 I've looked at implementing the following in helpers.py
![image](https://user-images.githubusercontent.com/14958920/135728490-6db4da96-ea54-4a2f-9988-aa291b4a20e7.png)

On a test of 70 files totalling 13.8GB this reduced the calculation time from 2m56s to 1m43s. Not sure if that's a big enough improvement but we could definitely look at reducing the overall byte size of each file that is checked (this does 250mb, 100mb resulted in a total time of 1m12s).

**Comment by z1pti3** [comment]
What does this do to the safety of the checksum hash function? Does it give the possibility of files not being cryptographic checked fully?

Do we need to secure checksum the files?

**Comment by b1scuit-thi3f** [comment]
So I did consider that, which is why I included the os.path.gmtime function call, which should get the timestamp of last file modification. Perhaps if we require more security over speed we can look at quicker hashing methods?

**Comment by z1pti3** [comment]
What about if we increase the block size from 4096 to 65535. I think that not hashing the full file does pose a risk when we come to do automatic updates across the cluster and platform.

**Comment by b1scuit-thi3f** [comment]
This seemed to reduce the overall time by only 3s unfortunately. I have done a bit more research and tried a few ways to speed up the results but I think we have already implemented the fastest checking we can without compromising on the cryptographic integrity.

**Comment by z1pti3** [comment]
What about if we moved storage into a none cryptographic integrity checksum function but kept system and plugins etc as is? Would that give us the best of both worlds?

**Comment by b1scuit-thi3f** [comment]
I've pushed b57acdf376ae53f68a3d51764ee79dc07aa5369b.
This will set the limit to 25mb for all storage files. This can be changed in a new storage setting object.
