### ISSUE TITLE
[Bug] subFlow with multiple paths does not return back last flow event data correctly

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#237]
subFlows that look like this with multiple paths 

![image](https://user-images.githubusercontent.com/81556695/135763146-acbff103-ab3c-4c9a-a86b-747903f0c17a.png)

If the alternative path is used the data output at the end of the subFlow is incorrect and does not contain the vars. In my case this is if the top flow is used.

As a work around I have had to use eventData to store data

**Comment by z1pti3** [comment]
This is in part expected due to how the flow executes but I understand how this is confusing for users. I think a new action maybe required to handle the return of data from subFlow. This same object maybe an option for breaking out of loops early as well.

**Comment by z1pti3** [comment]
Break object has been added and can be used to exit out of a subFlow early
