### ISSUE TITLE
[Bug] Cannot Compare Decimals in logicString

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#241]
I have discovered that it is not possible to compare values if one is a decimal written by the user into the logicString. For example, the logic string `if 1 < .2` results in the below screenshot.
![image](https://user-images.githubusercontent.com/14958920/137988283-c43d4cc8-1c1e-490f-8a48-53ff62a3661c.png)

I believe this has a workaround which is encapsulate the value in quotes, meaning it is passed safely through the function until it reaches the typecast at which point it is successfully added as a float. For example:
`if 1 < ".2"`

**Comment by b1scuit-thi3f** [comment]
Actually the quotes do not fix it!

**Comment by b1scuit-thi3f** [comment]
Testing if the following regex will work (added \. to the various capture groups for alphanum):
```
((\"(.*?[^\\])\"|([a-zA-Z0-9\.]+(\[(.*?)\])+)|([a-zA-Z0-9\.]+(\((.*?)(\)\)|\)))+)|\[(.*?)\]|([a-zA-Z0-9\.]*)))\s?( not match | match | not in | in |==|!=|>=|>|<=|<)\s?((\"(.*?[^\\])\"|([a-zA-Z0-9\.]+(\[(.*?)\])+)|([a-zA-Z0-9\.]+(\((.*?)(\)\)|\))( |$))+)|\[(.*?)\]|([a-zA-Z0-9\.]*)))
```

**Comment by u-n-i-c-o-rn** [comment]
I have also been looking at this in relation to an issue with function calls and extra spaces. I think building on what I have already posted as a pull request that you want this?

```
((\"(.*?[^\\])\"|([a-zA-Z0-9]+(\[(.*?)\])+)|([a-zA-Z0-9]+(\((.*?)(\)\)|\)))+)|\[(.*?)\]|([a-zA-Z0-9\.]*)))\s?( not match | match | not in | in |==|!=|>=|>|<=|<)\s?((\"(.*?[^\\])\"|([a-zA-Z0-9]+(\[(.*?)\])+)|([a-zA-Z0-9]+(\((.*?)(\)\)|\))(|$))+)|\[(.*?)\]|([a-zA-Z0-9\.]*)))
```

**Comment by z1pti3** [comment]
Updated the logic string to include both of these recommendations. The changes have passed all of the logic regex tests.
