### ISSUE TITLE
[Bug] Cannot rename storage files

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#271]
**Describe the bug**
Non admin users cannot rename a storage file once uploaded. They get a 500 Server Error instead.

**To Reproduce**
Login to jimi as a non-admin user who can upload to storage. Upload the file and then try to rename.

**Expected behaviour**
The user should be able to rename the object.

**Comment by u-n-i-c-o-rn** [comment]
+1 for a quick fix on this I am facing the same issue after I started to rollout to more users

**Comment by b1scuit-thi3f** [comment]
https://github.com/z1pti3/jimi/blob/59588fbd73821fde2da6ebb7114f2fa485c55c75/core/storage.py#L144-L148

Looks like this might be the issue

I don't think edit is a valid acl type to look for. Should this be write?
