### ISSUE TITLE
Override form data - var display name must equal core action varname

### ISSUE THREAD

**Issue by 0xSecEng** [z1pti3/jimi#35]
Could you please add functionality which would allow the display name to store a different value as opposed to the value located in the core action class. I'll be able to use the generic values instead of creating my own (as I'll be able to change the display name)

Thanks

**Comment by z1pti3** [comment]
It is now possible to include a "label" key withn the webUI formData dictionary to override the default name - This is optional

formData.append({"type" : "input", "schemaitem" : "name", "textbox" : classObject.name, "label" : "lol"})
