### ISSUE TITLE
Optional Visibility for Object Form Items

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#37]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Currently all form items are shown. It would be neater if we could hide certain items unless a certain requirement is met, e.g. a checkbox. For example, in the Humio plugin we have a number of Humio overrides. If the override checkbox is not ticked we should hide the four other items.

**Comment by z1pti3** [comment]
![image](https://user-images.githubusercontent.com/66521110/123472986-d73e0c80-d5ef-11eb-8c6a-c7313b8f5279.png)
