### ISSUE TITLE
Mandatory Fields

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#42]
**Is your feature request related to a problem? Please describe.**
Some fields should be required as mandatory to be completed/filled in for a form to save. This would avoid users maybe missing critical fields such as entity in assets, or searchRepository in Humio. 

**Describe the solution you'd like**
This could be done on client-side as this might be easier to override the individual form items like how we do for tool tips etc, but server-side would also be beneficial for future-proofing it.

**Describe alternatives you've considered**
Telling the users to do it properly. But unfortunately users are stupid sometimes. e.g. myself.

**Comment by z1pti3** [comment]
This can now be done as follows:

formData.append({"type" : "input", "schemaitem" : "comment", "textbox" : classObject.comment, "required" : True/False})
