### ISSUE TITLE
Alert Users When Modifying Shared Object

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#50]
**Is your feature request related to a problem? Please describe.**
Something that we run into now and again is when an object is mirrored (as in a direct copy of the object, rather than a duplicate) and is subsequently changed, all other copies are of course changed as well. It would be useful to be able to identify somehow if an object is re-used anywhere else.

**Describe the solution you'd like**
When a user attempts to make a change, perhaps a popup letting them know that the object is shared? Alternatively, we could have some sort of icon/indicator that lets a user easily identify shared objects.

**Comment by z1pti3** [comment]
I would avoid a message when saving as that may get annoying? But like the idea and think that maybe some way to identify the fact it is used elsewhere would be best. 

Maybe we include this feature with one that lets you locate the other locations it is used as well?

**Comment by b1scuit-thi3f** [comment]
Yes I think you are right. 
And are you talking about a "where used" item in the context menu? That would be quite useful I think!

**Comment by z1pti3** [comment]
Yes I think where-used in the context menu is a great idea it can open a list which you can then go to and focus on
