### ISSUE TITLE
Overhaul - Plugin System 

### ISSUE THREAD

**Issue by z1pti3** [z1pti3/jimi#53]
The jimi plugin system is core to its functionality and although it is functional there are a number of items that need to be overhauled.

*Core*
* Update
* Uninstall and Cleanup
* Enable and Disable
* Dependency checking and improved error handling
* Core API

*Web*
* Plugin view/panel + upgrade and install options
* Web API
* Static Includes
* Component Framework
* Dashboard / visualization Framework

*Documentation*

**Comment by b1scuit-thi3f** [comment]
To expand on dependency checking - I'm planning to add jimiVersion as well as version to the main plugin files. Let me know what you think

**Comment by z1pti3** [comment]
Should we add jimiMinVersion, jimiMaxVersion and then if these are unset use todays behaviour. Would be good if these could be separate as well i.e.

jimiMinVersion = "1.8"

Would result in only installing on jimi whereby the version is 1.8+

If you used max and min together you could lock a plugin to only install between 1.8 and 2.0

Would it also be worth having an versionCheckOverride bool so that a dev can handle the version within the plugin itself. You could have a plugin that works for both 1.0 and 2.0 but just some features are disabled by the dev.

--------------------------------------

Bit unrelation but a check for other dependant plugins would also be cool like inga which requires remote to be installed

**Comment by b1scuit-thi3f** [comment]
Good shout, min and max definitely make sense!
And yeah I think the more control given to devs the better (where it doesn't impact the security or integrity of the system of course lol)
