### ISSUE TITLE
Restarted Node Doesn't Respect Trigger's System ID

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#9]
Just noticed that when I restarted Node 1, a trigger running on Node 3 will re-run as if it has been reset.
This possibly only affects failed triggers.

I suspect we just need to update the trigger reset function (below) in system install to only search for triggers that match its system ID?

https://github.com/z1pti3/jimi/blob/3bb9804308ab05b177e54d7a90d8d49fb38f39d4/system/install.py#L92-L103

**Comment by z1pti3** [comment]
Added a fix for this within 091c75f32fab86c10fdf7659410999569cf9df1d

The system no longer auto resets triggers but instead if a menu item within the core menu
